import { Geist, Geist_Mono, Noto_Sans } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const arnoPro = localFont({
  src: [
    {
      path: "./fonts/fonnts.com-Arno-Pro-.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/fonnts.com-Arno-Pro-Smbd-.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/arnopro_bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/ArnoProSemiboldItalic.otf",
      weight: "600",
      style: "italic",
    },
  ],
  variable: "--font-arno-pro",
  
});

const arnoCaption = localFont({
  src: [
    {
      path: "./fonts/arnopro_caption.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/arnopro_boldcaption.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-arno-caption",
});

const corsiva = localFont({
  src: [
    {
      path: "./fonts/Monotype-Corsiva-Regular.ttf", 
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Monotype-Corsiva-Bold.ttf", 
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-corsiva",
});

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700", "800"],
});

const zapfino = localFont({
  src: "./fonts/Zapfino.ttf",
  variable: "--font-zapfino",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${arnoPro.variable} ${corsiva.variable} ${zapfino.variable}  ${arnoCaption.variable}  ${notoSans.variable}
`}
    >
      <body>{children}</body>
    </html>
  );
}
